TEMPLATE = {   'bullet_char': '•',
    'fonts': {   'body': {   'bold': False,
                             'color': '000000',
                             'name': 'ArialMT',
                             'size': 12},
                 'bullet': {   'bold': False,
                               'color': '000000',
                               'name': 'ArialMT',
                               'size': 12},
                 'contact': {   'bold': False,
                                'color': '444444',
                                'name': 'Calibri',
                                'size': 10},
                 'dates': {   'bold': False,
                              'color': '666666',
                              'name': 'Calibri',
                              'size': 10},
                 'heading1': {   'bold': True,
                                 'color': '434343',
                                 'name': 'Arial',
                                 'size': 16},
                 'heading2': {   'bold': True,
                                 'color': '333333',
                                 'name': 'Calibri',
                                 'size': 11},
                 'name_header': {   'bold': True,
                                    'color': '434343',
                                    'name': 'Arial',
                                    'size': 16}},
    'name': 'Uploaded',
    'page_margins': {'bottom': 1.0, 'left': 1.0, 'right': 1.0, 'top': 1.0},
    'section_divider': True,
    'spacing': {   'after_section_pt': 4,
                   'before_section_pt': 10,
                   'bullet_indent_cm': 0.5,
                   'line_spacing': 1.15}}
